### Tensor
#### array/matrix -like datatype

### Generation

In [2]:
import torch 
import numpy as np

In [3]:
# 1) Generating directly from Python list 
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [4]:
# 2) from NumPy array
np_array=np.array(data)
x_np= torch.from_numpy(np_array)
# Tensor.numpy(): Tensor --> numpy
# x_np & np_array share memory: changing one would automatically change the other

In [5]:
# 3) from existing Tensor 
x_ones=torch.ones_like(x_data)
# This generates a Tensor consisting of 1 that has the same shape & dtype as x_data
x_rand =torch.rand_like(x_data, dtype=torch.float)

# *_like() --> keeps the form of the original Tensor

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8075, 0.9111],
        [0.1643, 0.0924]])


In [6]:
# 4) random & const. 
shape = (2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.0156, 0.0338, 0.1041],
        [0.0937, 0.5726, 0.8000]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attribute 
#### shape, datatype and the device tensor is stored

In [7]:
tensor=torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


### Operation
#### e.g. transposing, indexing, slicing, calculation, linear algebra, random sampling,...

In [8]:
# 1. Moving Tensors Between CPU <-> GPU
# By default, Tensors are created in CPU memory.
# If a GPU is available, it is possible to move Tensors to the GPU using .to("cuda") or .cuda() for significantly faster computation.
# However, frequently transferring large Tensors between devices adds overhead—so try to keep them on a single device whenever possible.

if torch.cuda.is_available():
    tensor=tensor.to("cuda")

In [10]:
# 2. Indexing & Slicing
tensor = torch.ones(4,4)

# 1st row
print(tensor[0])

# 1st col
print(tensor[:, 0])

# last col
print(tensor[..., -1])

# Changing all the values of 2nd col to zero
tensor[:, 1]=0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# 3. Concatenataion VS. Stacking
# torch.cat = concatenating multiple Tensors along pre-existing axis
# torch.stack = generating additional axis and stacking Tensors along that axis

# (4x4 Tensor --> concatenate three times along dim=1 --> 4X12 Tensor)
t1=torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [16]:
# 4. Arithmetic Operations
# matrix multplication (y1, y2, y3: hold the same values)
# tensor.T --> transpose of tensor
y1= tensor @ tensor.T
y2= tensor.matmul(tensor.T)

y3= torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) # this could reduce overhead 

# element-wise product (z1, z2, z3: hold the same values)
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3=torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

# Single-element Tensors 
# When aggregating a Tensor into a single-element Tensor (e.g., via sum()),
# use .item() to convert it to a native Python number
agg=tensor.sum()
agg_item=agg.item()

print(agg, type(agg)) # Tensor
print(agg_item, type(agg_item)) #float


# In-place operations
# Operations that store their result in the operand are called in-place and use a trailing underscore.
# For example, x.copy_(y) or x.t_() modify x directly.
print(tensor)
tensor.add_(5)
print(tensor)

# Note:
# In-place operations save some memory but immediately overwrite the computation history,
# which can interfere with automatic differentiation (gradient calculation).
# Therefore, their use is generally discouraged.

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### NumPy Bridge

In [19]:
# 1) Tensor -> Numpy: Convert a Tensor to a NumPy array (shares the same memory)
t=torch.ones(5)
print(t)
n=t.numpy()
print(n)

# In-place addition on the Tensor will reflect in the NumPy array
t.add_(3)
print(t)
print(n)

# 2) Numpy -> Tensor: Convert a NumPy array to a Tensor (shares the same memory)
n= np.ones(5)
t= torch.from_numpy(n)

print(n)
print(t)

np.add(n, 1, out=n)
print(n)
print(t)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
